### PR TITLE
Add support for macOS (AppKit) using the NSUI package

### PR DESCRIPTION
**Pull request by martindufort**
Here's my pull request to add AppKit support using NSUI. 

Sorry this is a rather large PR. 
I would be happy to discuss changes and modifications with you. 
There are still some elements that are *in process* but I would rather submit it now and then continue moving forward after approval. 

If you feel this is going too far from your original approach, let me know so we can collaborate and make this work. 

I also updated the example `PillView` app which was not demonstrating the usage. 
I can PR this one also after thes changes are approved.

--- Changes ---
- Decided go switch from UXKit to NSUI because it is a simpler package (#26).
- I have derived PillView from NSUIView (aka UIView) because it makes things simpler (#27).
- Added autoresizing masks to keep pill center in container (#24)
- Add ability to update Show Task message will being displayed. 
- Add ability to state time before error message is dismissed.
- Add ability to specify custom Font for the message. 
- Remove PillView From hierarchy upon dismissal (#25).
 
--- In Process ---
- Position of pillView with offset from edge (top, bottom)
- Vertically centering of messages within pill if height is customized

### CODE REVIEW

**Comment by martindufort** [comment]
Preview of the updated PillView working on iOS + Catalyst 
Only thing left to do is the PillPosition (bottom, top, offset) but I would rather close this PR and work on this in a new one. 

Let me know... 
https://github.com/Awesomeplayer165/PillboxView/assets/28934641/111fc710-aa83-444a-85b6-d15d1e848841
https://github.com/Awesomeplayer165/PillboxView/assets/28934641/edbdab92-e416-4fea-834f-e4d92cdfd4c6

**Comment by martindufort** [comment]
Don't hesitate to ping me if you need help with this PR review. 
In my fork, I have disabled your 'iOS starter workflow' to ensure everything runs correctly.

**Review by Awesomeplayer165 — APPROVED** [review]
LGTM

**Comment by martindufort** [comment]
Super.  I will move forward with the PR that allows positioning the PillView either at the top or the bottom.

That function is already working on my side.

**Comment by Awesomeplayer165** [comment]
Sounds good. Maybe adding more padding to keep it inside safe areas would be nice. Thanks!

**Comment by martindufort** [comment]
I was thinking of adding the property `fromSafeAreaTopEdge?` and `fromSafeAreaBottomEdge?` to the PillPosition structure. And then use the containing view `safeAreaLayoutGuide` to do the positioning. 

And because a `safeArea` does not exist on macOS, those are optionals. 

LMK.

**Pull request merged**
